id = "scss"
name = "SCSS"
description = "SCSS support"
version = "0.0.4"
schema_version = 1
authors = ["Raunak Raj <bajrangcoders@gmail.com>"]
repository = "https://github.com/bajrangCoder/zed-scss"

[grammars.scss]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-scss"
commit = "9ab738d22bb248771d42e8678d1a307d14990df1"

[language_servers.scss-lsp]
name = "SCSS Language Server"
language = "SCSS"

[language_servers.some-sass-lsp]
name = "Some Sass Language Server"
language = "SCSS"
